import { expect, test } from "@playwright/test"

test.beforeEach(async ({ page }) => {
  await page.goto("http://127.0.0.1:5173/")
  await page.evaluate(() => localStorage.clear())
  await page.reload()
})

test("completes the first-passport happy path", async ({ page }) => {
  await page.getByRole("button", { name: /my first passport/i }).click()
  await expect(page.getByRole("heading", { name: "Sign in to continue" })).toBeVisible()
  await page.getByRole("button", { name: /continue with mock sign-in/i }).click()
  const continueButton = page.getByRole("button", { name: /^continue/i })
  for (const heading of ["Personal & history", "Family details", "Contacts & legal", "Address & office", "Passport options", "Documents"]) {
    await expect(page.getByRole("heading", { name: heading })).toBeVisible()
    await continueButton.click()
  }
  await expect(page.getByRole("heading", { name: "Review your application" })).toBeVisible()
  await page.getByText("I have reviewed the application and the official declaration.").click()
  await page.getByRole("button", { name: /submit mock application/i }).click()
  await expect(page.getByRole("heading", { name: "Choose an appointment" })).toBeVisible()
  await page.getByRole("button", { name: /PSK Bengaluru, Lalbagh/i }).click()
  await page.getByRole("button", { name: /continue to mock payment/i }).click()
  const selects = page.locator(".payment-content [data-slot='select-trigger']")
  await selects.nth(0).click()
  await page.getByRole("option", { name: "Thu, 03 Sep" }).click()
  await selects.nth(1).click()
  await page.getByRole("option", { name: "09:30" }).click()
  await page.getByRole("button", { name: /pay mock fee and confirm/i }).click()
  await expect(page.getByText("Mock payment failed")).toBeVisible()
  await page.getByRole("button", { name: /retry mock payment/i }).click()
  await expect(page.getByRole("button", { name: /view appointment summary/i })).toBeEnabled()
  await page.getByRole("button", { name: /view appointment summary/i }).click()
  await expect(page.getByRole("heading", { name: "Prepared for your appointment" })).toBeVisible()
})

test("saves, exits, and resumes at the correct stage", async ({ page }) => {
  await page.getByRole("button", { name: /my first passport/i }).click()
  await page.getByRole("button", { name: /continue with mock sign-in/i }).click()
  await page.getByRole("button", { name: /^continue/i }).click()
  await page.getByRole("button", { name: "Save & exit" }).click()
  await expect(page.getByRole("heading", { name: "Everything you have started." })).toBeVisible()
  const liveRow = page.locator(".applications-table tr.live")
  await expect(liveRow).toContainText("Family details")
  await expect(liveRow).toContainText("Stage 2 of 9")
  await liveRow.getByRole("button", { name: /^resume$/i }).click()
  await expect(page.getByRole("heading", { name: "Family details" })).toBeVisible()
})

test("lists every application with status, stage and office", async ({ page }) => {
  await page.getByRole("button", { name: /my first passport/i }).click()
  await page.getByRole("button", { name: /continue with mock sign-in/i }).click()
  await page.locator(".app-rail").getByRole("button", { name: "My applications" }).click()
  const rows = page.locator(".applications-table tbody tr")
  await expect(rows).toHaveCount(4)
  await expect(page.getByRole("columnheader", { name: "Status" })).toBeVisible()
  await expect(page.getByRole("columnheader", { name: "Stage" })).toBeVisible()
  await expect(page.getByRole("columnheader", { name: /office & contact/i })).toBeVisible()
  await page.getByRole("button", { name: "With the office" }).click()
  await expect(rows).toHaveCount(1)
  await expect(rows.first()).toContainText("Appointment booked")
  await page.getByRole("button", { name: "All" }).click()
  await page.getByRole("button", { name: "Cards" }).click()
  await expect(page.locator(".applications-cards [data-slot='card']")).toHaveCount(4)
})

test("the rail stays available and collapses to icons", async ({ page }) => {
  await page.getByRole("button", { name: /my first passport/i }).click()
  await page.getByRole("button", { name: /continue with mock sign-in/i }).click()
  const rail = page.locator(".app-rail")
  await expect(rail.getByRole("button", { name: "My applications" })).toBeVisible()
  await expect(rail.getByRole("button", { name: "Appointment" })).toBeDisabled()
  await page.getByRole("button", { name: "Collapse the sidebar" }).click()
  await expect(page.locator(".app-rail.collapsed")).toBeVisible()
  await expect(rail.getByRole("button", { name: "Documents" })).toBeVisible()
  await rail.getByRole("button", { name: "My applications" }).click()
  await expect(page.getByRole("heading", { name: "Everything you have started." })).toBeVisible()
  await expect(page.locator(".app-rail.collapsed")).toBeVisible()
  await page.getByRole("button", { name: "Expand the sidebar" }).click()
  await expect(page.locator(".app-rail.collapsed")).toHaveCount(0)
})

test("mobile exposes application navigation in a drawer", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("button", { name: /my first passport/i }).click()
  await page.getByRole("button", { name: /continue with mock sign-in/i }).click()
  await page.getByRole("button", { name: "Open application menu" }).click()
  for (const name of ["My applications", "Current stage", "Documents", "Help for this stage", "Save & exit", "Sign out"]) {
    await expect(page.getByRole("button", { name })).toBeVisible()
  }
})

test("the rail opens the document library as a full page beside it", async ({ page }) => {
  await page.getByRole("button", { name: /my first passport/i }).click()
  await page.getByRole("button", { name: /continue with mock sign-in/i }).click()
  const rail = page.locator(".app-rail")
  await rail.getByRole("button", { name: "Documents" }).click()
  await expect(page.getByRole("heading", { name: "Every document this journey involves." })).toBeVisible()
  // The point of the feedback: a page next to the rail, not a dialog over it.
  await expect(page.locator("[role='dialog']")).toHaveCount(0)
  await expect(rail).toBeVisible()
  await expect(page.locator(".doc-library-page")).toBeVisible()
  await expect(page.locator(".doc-library-item")).toHaveCount(3)
  await expect(page.locator(".doc-library-item").first()).toContainText("Stands behind")
  await expect(page.getByText("Which specific documents count")).toBeVisible()
  await expect(page.locator(".doc-library-aside")).toContainText("official accepted-document lists decide that")
  // The library is reference; the stage it points at is where a document is decided.
  await page.getByRole("button", { name: "Open Personal & history", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Personal & history" })).toBeVisible()
})
